file(GLOB MODULE_PB_SOURCES ${CMAKE_CURRENT_LIST_DIR}/*.pb-c.c)
set(MODULE_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/ctpb.c
    ${CMAKE_CURRENT_LIST_DIR}/ctpb_frame.c
    ${MODULE_PB_SOURCES}
)
set(MODULE_INCLUDES
    ${CMAKE_CURRENT_LIST_DIR}/include
    ${CMAKE_CURRENT_LIST_DIR}
)
