/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CTP.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CTP.pb-c.h"
void   ping_cmd__init
                     (PingCmd         *message)
{
  static const PingCmd init_value = PING_CMD__INIT;
  *message = init_value;
}
size_t ping_cmd__get_packed_size
                     (const PingCmd *message)
{
  assert(message->base.descriptor == &ping_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_cmd__pack
                     (const PingCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_cmd__pack_to_buffer
                     (const PingCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingCmd *
       ping_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingCmd *)
     protobuf_c_message_unpack (&ping_cmd__descriptor,
                                allocator, len, data);
}
void   ping_cmd__free_unpacked
                     (PingCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   version_cmd__init
                     (VersionCmd         *message)
{
  static const VersionCmd init_value = VERSION_CMD__INIT;
  *message = init_value;
}
size_t version_cmd__get_packed_size
                     (const VersionCmd *message)
{
  assert(message->base.descriptor == &version_cmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t version_cmd__pack
                     (const VersionCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &version_cmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t version_cmd__pack_to_buffer
                     (const VersionCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &version_cmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VersionCmd *
       version_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VersionCmd *)
     protobuf_c_message_unpack (&version_cmd__descriptor,
                                allocator, len, data);
}
void   version_cmd__free_unpacked
                     (VersionCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &version_cmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping_res__init
                     (PingRes         *message)
{
  static const PingRes init_value = PING_RES__INIT;
  *message = init_value;
}
size_t ping_res__get_packed_size
                     (const PingRes *message)
{
  assert(message->base.descriptor == &ping_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_res__pack
                     (const PingRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_res__pack_to_buffer
                     (const PingRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingRes *
       ping_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingRes *)
     protobuf_c_message_unpack (&ping_res__descriptor,
                                allocator, len, data);
}
void   ping_res__free_unpacked
                     (PingRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   version_res__init
                     (VersionRes         *message)
{
  static const VersionRes init_value = VERSION_RES__INIT;
  *message = init_value;
}
size_t version_res__get_packed_size
                     (const VersionRes *message)
{
  assert(message->base.descriptor == &version_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t version_res__pack
                     (const VersionRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &version_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t version_res__pack_to_buffer
                     (const VersionRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &version_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VersionRes *
       version_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VersionRes *)
     protobuf_c_message_unpack (&version_res__descriptor,
                                allocator, len, data);
}
void   version_res__free_unpacked
                     (VersionRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &version_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctpcmd__init
                     (CTPCmd         *message)
{
  static const CTPCmd init_value = CTPCMD__INIT;
  *message = init_value;
}
size_t ctpcmd__get_packed_size
                     (const CTPCmd *message)
{
  assert(message->base.descriptor == &ctpcmd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctpcmd__pack
                     (const CTPCmd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctpcmd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctpcmd__pack_to_buffer
                     (const CTPCmd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctpcmd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTPCmd *
       ctpcmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTPCmd *)
     protobuf_c_message_unpack (&ctpcmd__descriptor,
                                allocator, len, data);
}
void   ctpcmd__free_unpacked
                     (CTPCmd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctpcmd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ctpres__init
                     (CTPRes         *message)
{
  static const CTPRes init_value = CTPRES__INIT;
  *message = init_value;
}
size_t ctpres__get_packed_size
                     (const CTPRes *message)
{
  assert(message->base.descriptor == &ctpres__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ctpres__pack
                     (const CTPRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ctpres__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ctpres__pack_to_buffer
                     (const CTPRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ctpres__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CTPRes *
       ctpres__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CTPRes *)
     protobuf_c_message_unpack (&ctpres__descriptor,
                                allocator, len, data);
}
void   ctpres__free_unpacked
                     (CTPRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ctpres__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define ping_cmd__field_descriptors NULL
#define ping_cmd__field_indices_by_name NULL
#define ping_cmd__number_ranges NULL
const ProtobufCMessageDescriptor ping_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingCmd",
  "PingCmd",
  "PingCmd",
  "",
  sizeof(PingCmd),
  0,
  ping_cmd__field_descriptors,
  ping_cmd__field_indices_by_name,
  0,  ping_cmd__number_ranges,
  (ProtobufCMessageInit) ping_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define version_cmd__field_descriptors NULL
#define version_cmd__field_indices_by_name NULL
#define version_cmd__number_ranges NULL
const ProtobufCMessageDescriptor version_cmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VersionCmd",
  "VersionCmd",
  "VersionCmd",
  "",
  sizeof(VersionCmd),
  0,
  version_cmd__field_descriptors,
  version_cmd__field_indices_by_name,
  0,  version_cmd__number_ranges,
  (ProtobufCMessageInit) version_cmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping_res__field_descriptors[1] =
{
  {
    "alive",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PingRes, alive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping_res__field_indices_by_name[] = {
  0,   /* field[0] = alive */
};
static const ProtobufCIntRange ping_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingRes",
  "PingRes",
  "PingRes",
  "",
  sizeof(PingRes),
  1,
  ping_res__field_descriptors,
  ping_res__field_indices_by_name,
  1,  ping_res__number_ranges,
  (ProtobufCMessageInit) ping_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor version_res__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VersionRes, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned version_res__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange version_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor version_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VersionRes",
  "VersionRes",
  "VersionRes",
  "",
  sizeof(VersionRes),
  1,
  version_res__field_descriptors,
  version_res__field_indices_by_name,
  1,  version_res__number_ranges,
  (ProtobufCMessageInit) version_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctpcmd__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CTPCmd, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CTPCmd, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CTPCmd, type),
    &cmd_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ping",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CTPCmd, body_case),
    offsetof(CTPCmd, ping),
    &ping_cmd__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CTPCmd, body_case),
    offsetof(CTPCmd, version),
    &version_cmd__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctpcmd__field_indices_by_name[] = {
  1,   /* field[1] = handle */
  0,   /* field[0] = id */
  3,   /* field[3] = ping */
  2,   /* field[2] = type */
  4,   /* field[4] = version */
};
static const ProtobufCIntRange ctpcmd__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ctpcmd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTPCmd",
  "CTPCmd",
  "CTPCmd",
  "",
  sizeof(CTPCmd),
  5,
  ctpcmd__field_descriptors,
  ctpcmd__field_indices_by_name,
  2,  ctpcmd__number_ranges,
  (ProtobufCMessageInit) ctpcmd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ctpres__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CTPRes, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ping",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CTPRes, body_case),
    offsetof(CTPRes, ping),
    &ping_res__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CTPRes, body_case),
    offsetof(CTPRes, version),
    &version_res__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ctpres__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = ping */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange ctpres__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ctpres__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CTPRes",
  "CTPRes",
  "CTPRes",
  "",
  sizeof(CTPRes),
  3,
  ctpres__field_descriptors,
  ctpres__field_indices_by_name,
  2,  ctpres__number_ranges,
  (ProtobufCMessageInit) ctpres__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cmd_type__enum_values_by_number[3] =
{
  { "CMD_EASY", "CMD_TYPE__CMD_EASY", 0 },
  { "CMD_COMP", "CMD_TYPE__CMD_COMP", 1 },
  { "CMD_SWIT", "CMD_TYPE__CMD_SWIT", 2 },
};
static const ProtobufCIntRange cmd_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex cmd_type__enum_values_by_name[3] =
{
  { "CMD_COMP", 1 },
  { "CMD_EASY", 0 },
  { "CMD_SWIT", 2 },
};
const ProtobufCEnumDescriptor cmd_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CmdType",
  "CmdType",
  "CmdType",
  "",
  3,
  cmd_type__enum_values_by_number,
  3,
  cmd_type__enum_values_by_name,
  1,
  cmd_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
