/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CTP.proto */

#ifndef PROTOBUF_C_CTP_2eproto__INCLUDED
#define PROTOBUF_C_CTP_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct PingCmd PingCmd;
typedef struct VersionCmd VersionCmd;
typedef struct PingRes PingRes;
typedef struct VersionRes VersionRes;
typedef struct CTPCmd CTPCmd;
typedef struct CTPRes CTPRes;


/* --- enums --- */

typedef enum _CmdType {
  CMD_TYPE__CMD_EASY = 0,
  CMD_TYPE__CMD_COMP = 1,
  CMD_TYPE__CMD_SWIT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CMD_TYPE)
} CmdType;

/* --- messages --- */

struct  PingCmd
{
  ProtobufCMessage base;
};
#define PING_CMD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ping_cmd__descriptor) \
 }


struct  VersionCmd
{
  ProtobufCMessage base;
};
#define VERSION_CMD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&version_cmd__descriptor) \
 }


struct  PingRes
{
  ProtobufCMessage base;
  protobuf_c_boolean alive;
};
#define PING_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ping_res__descriptor) \
, 0 }


struct  VersionRes
{
  ProtobufCMessage base;
  char *version;
};
#define VERSION_RES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&version_res__descriptor) \
, (char *)protobuf_c_empty_string }


typedef enum {
  CTPCMD__BODY__NOT_SET = 0,
  CTPCMD__BODY_PING = 10,
  CTPCMD__BODY_VERSION = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CTPCMD__BODY__CASE)
} CTPCmd__BodyCase;

struct  CTPCmd
{
  ProtobufCMessage base;
  /*
   * 命令id,响应时原样带回
   */
  uint32_t id;
  /*
   * 上下文句柄,仅CMD_COMP时有效
   */
  uint32_t handle;
  /*
   * 指令类型,设备据此判断是否需要创建上下文
   */
  CmdType type;
  CTPCmd__BodyCase body_case;
  union {
    PingCmd *ping;
    VersionCmd *version;
  };
};
#define CTPCMD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctpcmd__descriptor) \
, 0, 0, CMD_TYPE__CMD_EASY, CTPCMD__BODY__NOT_SET, {0} }


typedef enum {
  CTPRES__BODY__NOT_SET = 0,
  CTPRES__BODY_PING = 10,
  CTPRES__BODY_VERSION = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CTPRES__BODY__CASE)
} CTPRes__BodyCase;

struct  CTPRes
{
  ProtobufCMessage base;
  /*
   * 对应命令id,与CTPCmd.id一致
   */
  uint32_t id;
  CTPRes__BodyCase body_case;
  union {
    PingRes *ping;
    VersionRes *version;
  };
};
#define CTPRES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ctpres__descriptor) \
, 0, CTPRES__BODY__NOT_SET, {0} }


/* PingCmd methods */
void   ping_cmd__init
                     (PingCmd         *message);
size_t ping_cmd__get_packed_size
                     (const PingCmd   *message);
size_t ping_cmd__pack
                     (const PingCmd   *message,
                      uint8_t             *out);
size_t ping_cmd__pack_to_buffer
                     (const PingCmd   *message,
                      ProtobufCBuffer     *buffer);
PingCmd *
       ping_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ping_cmd__free_unpacked
                     (PingCmd *message,
                      ProtobufCAllocator *allocator);
/* VersionCmd methods */
void   version_cmd__init
                     (VersionCmd         *message);
size_t version_cmd__get_packed_size
                     (const VersionCmd   *message);
size_t version_cmd__pack
                     (const VersionCmd   *message,
                      uint8_t             *out);
size_t version_cmd__pack_to_buffer
                     (const VersionCmd   *message,
                      ProtobufCBuffer     *buffer);
VersionCmd *
       version_cmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   version_cmd__free_unpacked
                     (VersionCmd *message,
                      ProtobufCAllocator *allocator);
/* PingRes methods */
void   ping_res__init
                     (PingRes         *message);
size_t ping_res__get_packed_size
                     (const PingRes   *message);
size_t ping_res__pack
                     (const PingRes   *message,
                      uint8_t             *out);
size_t ping_res__pack_to_buffer
                     (const PingRes   *message,
                      ProtobufCBuffer     *buffer);
PingRes *
       ping_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ping_res__free_unpacked
                     (PingRes *message,
                      ProtobufCAllocator *allocator);
/* VersionRes methods */
void   version_res__init
                     (VersionRes         *message);
size_t version_res__get_packed_size
                     (const VersionRes   *message);
size_t version_res__pack
                     (const VersionRes   *message,
                      uint8_t             *out);
size_t version_res__pack_to_buffer
                     (const VersionRes   *message,
                      ProtobufCBuffer     *buffer);
VersionRes *
       version_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   version_res__free_unpacked
                     (VersionRes *message,
                      ProtobufCAllocator *allocator);
/* CTPCmd methods */
void   ctpcmd__init
                     (CTPCmd         *message);
size_t ctpcmd__get_packed_size
                     (const CTPCmd   *message);
size_t ctpcmd__pack
                     (const CTPCmd   *message,
                      uint8_t             *out);
size_t ctpcmd__pack_to_buffer
                     (const CTPCmd   *message,
                      ProtobufCBuffer     *buffer);
CTPCmd *
       ctpcmd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctpcmd__free_unpacked
                     (CTPCmd *message,
                      ProtobufCAllocator *allocator);
/* CTPRes methods */
void   ctpres__init
                     (CTPRes         *message);
size_t ctpres__get_packed_size
                     (const CTPRes   *message);
size_t ctpres__pack
                     (const CTPRes   *message,
                      uint8_t             *out);
size_t ctpres__pack_to_buffer
                     (const CTPRes   *message,
                      ProtobufCBuffer     *buffer);
CTPRes *
       ctpres__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ctpres__free_unpacked
                     (CTPRes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PingCmd_Closure)
                 (const PingCmd *message,
                  void *closure_data);
typedef void (*VersionCmd_Closure)
                 (const VersionCmd *message,
                  void *closure_data);
typedef void (*PingRes_Closure)
                 (const PingRes *message,
                  void *closure_data);
typedef void (*VersionRes_Closure)
                 (const VersionRes *message,
                  void *closure_data);
typedef void (*CTPCmd_Closure)
                 (const CTPCmd *message,
                  void *closure_data);
typedef void (*CTPRes_Closure)
                 (const CTPRes *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cmd_type__descriptor;
extern const ProtobufCMessageDescriptor ping_cmd__descriptor;
extern const ProtobufCMessageDescriptor version_cmd__descriptor;
extern const ProtobufCMessageDescriptor ping_res__descriptor;
extern const ProtobufCMessageDescriptor version_res__descriptor;
extern const ProtobufCMessageDescriptor ctpcmd__descriptor;
extern const ProtobufCMessageDescriptor ctpres__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_CTP_2eproto__INCLUDED */
