/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor.pb-c.h"
void   sensor_data__init
                     (SensorData         *message)
{
  static const SensorData init_value = SENSOR_DATA__INIT;
  *message = init_value;
}
size_t sensor_data__get_packed_size
                     (const SensorData *message)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_data__pack
                     (const SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_data__pack_to_buffer
                     (const SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorData *
       sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorData *)
     protobuf_c_message_unpack (&sensor_data__descriptor,
                                allocator, len, data);
}
void   sensor_data__free_unpacked
                     (SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue sensor_data__sensor_type__enum_values_by_number[3] =
{
  { "TEMP_HUMIDITY", "SENSOR_DATA__SENSOR_TYPE__TEMP_HUMIDITY", 0 },
  { "PRESSURE", "SENSOR_DATA__SENSOR_TYPE__PRESSURE", 1 },
  { "LIGHT", "SENSOR_DATA__SENSOR_TYPE__LIGHT", 2 },
};
static const ProtobufCIntRange sensor_data__sensor_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex sensor_data__sensor_type__enum_values_by_name[3] =
{
  { "LIGHT", 2 },
  { "PRESSURE", 1 },
  { "TEMP_HUMIDITY", 0 },
};
const ProtobufCEnumDescriptor sensor_data__sensor_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SensorData.SensorType",
  "SensorType",
  "SensorData__SensorType",
  "",
  3,
  sensor_data__sensor_type__enum_values_by_number,
  3,
  sensor_data__sensor_type__enum_values_by_name,
  1,
  sensor_data__sensor_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sensor_data__field_descriptors[5] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_device_id),
    offsetof(SensorData, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SensorData, has_temperature),
    offsetof(SensorData, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SensorData, has_humidity),
    offsetof(SensorData, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_timestamp),
    offsetof(SensorData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SensorData, has_type),
    offsetof(SensorData, type),
    &sensor_data__sensor_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_data__field_indices_by_name[] = {
  0,   /* field[0] = device_id */
  2,   /* field[2] = humidity */
  1,   /* field[1] = temperature */
  3,   /* field[3] = timestamp */
  4,   /* field[4] = type */
};
static const ProtobufCIntRange sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SensorData",
  "SensorData",
  "SensorData",
  "",
  sizeof(SensorData),
  5,
  sensor_data__field_descriptors,
  sensor_data__field_indices_by_name,
  1,  sensor_data__number_ranges,
  (ProtobufCMessageInit) sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
