/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor.proto */

#ifndef PROTOBUF_C_sensor_2eproto__INCLUDED
#define PROTOBUF_C_sensor_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SensorData SensorData;


/* --- enums --- */

typedef enum _SensorData__SensorType {
  SENSOR_DATA__SENSOR_TYPE__TEMP_HUMIDITY = 0,
  SENSOR_DATA__SENSOR_TYPE__PRESSURE = 1,
  SENSOR_DATA__SENSOR_TYPE__LIGHT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SENSOR_DATA__SENSOR_TYPE)
} SensorData__SensorType;

/* --- messages --- */

/*
 * 示例: 传感器数据上报
 */
struct  SensorData
{
  ProtobufCMessage base;
  /*
   * 设备ID
   */
  protobuf_c_boolean has_device_id;
  uint32_t device_id;
  /*
   * 温度
   */
  protobuf_c_boolean has_temperature;
  float temperature;
  /*
   * 湿度
   */
  protobuf_c_boolean has_humidity;
  float humidity;
  /*
   * 时间戳
   */
  protobuf_c_boolean has_timestamp;
  uint32_t timestamp;
  protobuf_c_boolean has_type;
  SensorData__SensorType type;
};
#define SENSOR_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sensor_data__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, SENSOR_DATA__SENSOR_TYPE__TEMP_HUMIDITY }


/* SensorData methods */
void   sensor_data__init
                     (SensorData         *message);
size_t sensor_data__get_packed_size
                     (const SensorData   *message);
size_t sensor_data__pack
                     (const SensorData   *message,
                      uint8_t             *out);
size_t sensor_data__pack_to_buffer
                     (const SensorData   *message,
                      ProtobufCBuffer     *buffer);
SensorData *
       sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sensor_data__free_unpacked
                     (SensorData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SensorData_Closure)
                 (const SensorData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sensor_data__descriptor;
extern const ProtobufCEnumDescriptor    sensor_data__sensor_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sensor_2eproto__INCLUDED */
